### ISSUE TITLE
Cannot restrict a KILL signal

### ISSUE THREAD

**Issue by nguyenvulong** [wilsonwr/bcc-lsm-scripts#1]
Hello, thanks for the great repo. I am testing it out now.
I tried to restrict a kill signal (for example, `kill 21840` (after searching for the PID)) but it did not work. Could you please have a look at the log.

Release
```
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
Kernel
```
 uname -a
Linux AMC_Test 5.12.0-051200-lowlatency #202104252130 SMP PREEMPT Sun Apr 25 21:36:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
❯ sudo ./mac_killtasks -D
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:76:
include/linux/compiler-clang.h:33:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redef
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:76:
include/linux/compiler-clang.h:34:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redef
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:76:
include/linux/compiler-clang.h:35:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redef
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
3 warnings generated.
^C% 
```

Also I am not sure I understand this correctly 

> The lsm= kernel parameter specifies a comma-delimited string of LSMs to enable at runtime. Add bpf to enable KRSI.

Do I need to recompile the kernel with certain parameters? And how to validate that everything is configured correctly. Thank you

**Comment by wilsonwr** [comment]
There is a good chance that these kinds of issues will continuously get in the way on Ubuntu 18.04, even with the newer kernel you're on. I'd recommend pushing up to Ubuntu 20.10 or newer to avoid various gotchas. For example, I just spun up an 18.04 VM and saw that glibc is older than you would want. Ubuntu 20.10 will also have the proper kernel parameter by default, if I'm not mistaken.

Specific to your last question: You can set the LSM parameters at compile or runtime. The compile-time settings can be founding on Ubuntu by running `zgrep CONFIG_LSM= /boot/config-<your_kernel_version>`. If "bpf" isn't in the list, then you can change that parameter at runtime as the system boots. Grub will let you press `e` on the menu to go into edit mode, where you can find the line that starts with `linux` and add the lsm= parameter. Section 4.2 of my paper linked in the README has more details about that.

**Comment by nguyenvulong** [comment]
After adding `lsm=bpf` in `/etc/default/grub` and reboot the server, it worked. 
My server is in a datacenter so it's a bit inconvenient to boot it interactively. 

Your writing from SANS is really inspiring and thanks so much for pioneering these working scripts. This is extremely useful for us devops people who don't really how the details of the kernel.
